### ISSUE TITLE
Cannot generate most of the mockups using Apple Watch series 8 mockup

### ISSUE THREAD

**Issue by NarijauskasMartynas** [oursky/mockuphone.com#131]
![laikrodis](https://github.com/user-attachments/assets/8847d867-19ee-4a3c-afc8-058d91e65daf)
I've been trying to use this screenshot, however all the series 8 mocks were failing (either infinite loading or error)

**Comment by pkong-ds** [comment]
@NarijauskasMartynas Thank you for using mockuphone! Can you provide some more details e.g.

1. What is your browser + version?
2. The actual file(s) you uploaded to mockuphone.com?
3. If possible, a screenshot video on how to reproduce the error?

---
Coz the setup below worked fine for me 👍 

## Environment
Browser: Chrome 130.0.6723.92 (Official Build) (arm64)
URL: https://mockuphone.com/model/apple-watch-series-8-45mm/

## Input
[github_NarijauskasMartynas.png](https://github.com/user-attachments/assets/8e0ed6d2-32c6-4965-9416-f6adfef3362c)

## Output

[apple-applewatch45mm-goldstainlesssteel-mockup (1).zip](https://github.com/user-attachments/files/17616555/apple-applewatch45mm-goldstainlesssteel-mockup.1.zip)

## Screenshot video

https://github.com/user-attachments/assets/706f3a8a-070e-4990-ba8e-e63b1e30ed79

**Comment by topalavlad** [comment]
Old issue but for me this seems to only work with the default color. Once I change to anything else, I get this in the console:

```
start mockup ./xx.png
pyodide.asm.js:9 orientation starlightsololoop-portrait
hoisted.ea656067.js:1 Get error while generating preview image Traceback (most recent call last):
  File "/lib/python311.zip/_pyodide/_base.py", line 540, in eval_code_async
    await CodeRunner(
  File "/lib/python311.zip/_pyodide/_base.py", line 365, in run_async
    await coroutine
  File "<exec>", line 15, in <module>
  File "<exec>", line 13, in runMockup
  File "/home/pyodide/mockup/mockup_generator.py", line 85, in mockup
    raise Exception("Cannot find orientation", self.orientation_name)
Exception: ('Cannot find orientation', 'starlightsololoop-portrait')
```

This seems to happen because the Apple Watch Series 8 entries use band-specific names (starlightsololoop-portrait, graysololoop-portrait, softgraysololoop-portrait) — different per color. The stale "starlightsololoop-portrait" string captured from Gold doesn't exist on Graphite, so lookup fails.

**Workaround:**
Select the color you want and then in the console run the lines below to reload the correct naming of the models:
```
  const dev = window.deviceInfo.devices.find(d => d.device_id === window.workerDeviceId);
  window.viewModel.orientations = dev.orientations.map(o => o.name);
  window.viewModel.selectedOrientation = window.viewModel.orientations[0];
```

**Comment by felixmachan** [comment]
Hi, I opened a PR to solve the issue.
